# Generated by Django 5.0.2 on 2024-10-08 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigoCategoria', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigoProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('codigoBarra', models.CharField(max_length=13)),
                ('codigoCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.categoria')),
            ],
        ),
    ]
